spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newnew?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: true
    show-sql: true

jwt:
  issuer: "newnew"
  key:
    access-key: "GxNfK0XvN7pM3jB2YqRtZl4s8dF1vC9qTzE5aWm2sUuLxOeH"
    refresh-key: "JrW4pD7aZsQ8xR1mTgB2yV5fNnL9kC3vEoH6qUuP0wYtSxMz"
  ttl:
    access: 3 #min
    refresh: 7 # days

openai:
  api:
    key: ${OPENAI-API-KEY:}